version: '3.7'

services:

  nb_publisher:
    image: nb_publisher
    build:
      context: .
      dockerfile: ./NitelikliBilisim.Publisher/Dockerfile
    restart: always
    depends_on:
      - "rabbitmq"

  nb_consumer:
    image: nb_consumer
    build:
      context: .
      dockerfile: ./NitelikliBilisim.Consumer/Dockerfile
    restart: always
    depends_on:
      - "nb_publisher"
      - "rabbitmq"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest