version: '3.4'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
<<<<<<< HEAD
<<<<<<< HEAD
=======
    networks:
      - devbox
>>>>>>> parent of c3fa381... niteliklitest.azurecr.io
=======
    networks:
      - niteliklitest.azurecr.io
>>>>>>> parent of e9fd9b1... .

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
<<<<<<< HEAD
<<<<<<< HEAD
=======
    networks:
      - devbox
>>>>>>> parent of c3fa381... niteliklitest.azurecr.io
=======
    networks:
      - niteliklitest.azurecr.io
>>>>>>> parent of e9fd9b1... .
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
<<<<<<< HEAD
<<<<<<< HEAD
    depends_on:
      - elasticsearch

=======
    networks:
      - devbox
    depends_on:
      - elasticsearch

networks:
  devbox:
    driver: bridge
>>>>>>> parent of c3fa381... niteliklitest.azurecr.io
=======
    networks:
      - niteliklitest.azurecr.io
    depends_on:
      - elasticsearch

networks:
  devbox:
    driver: niteliklitest.azurecr.io
>>>>>>> parent of e9fd9b1... .

